services:
  tienda-superkiosco-fvt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tienda-superkiosco-fvt
    # ports:
    #   - "5677:80"
    restart: unless-stopped
    networks:
      - redPrincipal

networks:
  redPrincipal:
    external: true