version: '3.8'
services:
  superkiosco-fvt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: superkiosco-fvt
    # ports:
    #   - "8080:80"
    env_file:
      - .env.example
    environment:
      # Puedes sobreescribir variables aquí si lo deseas
      # Ejemplo de configuración para entorno local/producción
      # 'desarrollo' o 'produccion'
      VITE_API_TOKEN="0sHJ5DDErt7obYkeaYTlAaVUZOfFSCb1OLew3ilm99687373"
      VITE_MODE="produccion"
      VITE_EMPRESA_ID="12"
      VITE_NOMBRE_NEGOCIO="Mi Negocio"
      VITE_API_URL="https://llfactura.com/api"
      VITE_API_RUBROS_URL="https://llfactura.com/api/rubros"
      VITE_GUARDAR_PRESUPUESTO="https://llfactura.com/api/guardarPresupuesto"
      VITE_LOGO_URL="https://res.cloudinary.com/dsen7wmue/image/upload/v1748752141/1/aaaa/228267_1748752139_aaaa.png"
      VITE_PRECIO1_LABEL="Precio de lista"
      VITE_PRECIO2_LABEL="Promoción"
      VITE_PRECIO3_LABEL="Pago tarjeta"
    restart: unless-stopped
