services:
  tienda-impotecno:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tienda-impotecno
    # ports:
    #   - "5174:80"
    restart: unless-stopped
    networks:
      - redPrincipal

networks:
  redPrincipal:
    external: true