services:
  tienda-su-mayorista:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tienda-su-mayorista
    # ports:
    #   - "5176:80"
    restart: unless-stopped
    networks:
      - redPrincipal

networks:
  redPrincipal:
    external: true
